# Generated by Django 4.1 on 2022-08-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountCodes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("usages", models.IntegerField()),
                ("discount_percentage", models.IntegerField()),
                ("code", models.TextField(default="IN7AUPBED93G")),
            ],
        ),
        migrations.CreateModel(
            name="MenuBar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=200)),
                ("logo", models.ImageField(upload_to="menu_logos")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=200)),
                ("image", models.ImageField(upload_to="products")),
                (
                    "category",
                    models.TextField(
                        choices=[("C", "Cake"), ("Coo", "Cookie"), ("B", "Beer")]
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
    ]
