# Generated by Django 4.1 on 2022-09-08 08:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=300)),
                ("image", models.ImageField(upload_to="categories")),
            ],
        ),
        migrations.AlterField(
            model_name="discountcodes",
            name="code",
            field=models.TextField(default=api.models.unique_rand, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.TextField(),
        ),
    ]
