# Generated by Django 4.1 on 2022-09-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuBar',
        ),
    ]
