# Generated by Django 4.1 on 2022-09-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mainpage_remove_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='title',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
